---
version: "3"
services:

  nginx:
    container_name: nginx
    image: "ngnix:1337"
    build:
      context : ./requirements/nginx
      dockerfile: Dockerfile
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www
    ports:
      - "443:443"
    networks:
      - inception
    restart: on-failure

  mariadb:
    container_name: mariadb
    image: mariadb:1337
    build:
      context : ./requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - db:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    restart: on-failure

  wordpress:
    container_name: wordpress
    image: wordpress:1337
    build:
      context : ./requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www
    networks:
      - inception
    env_file:
      - .env
    restart: on-failure
  
  redis:
    container_name: redis
    image: redis:1337
    build:
      context: ./requirements/bonus/redis
      dockerfile: Dockerfile
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www
    networks:
      - inception
    restart: on-failure
  
  adminer:
    container_name: adminer
    image: adminer:1337
    build:
      context: ./requirements/bonus/adminer
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    ports:
      - 8080:8080
    networks:
      - inception
    volumes:
      - wordpress:/var/www
    restart: on-failure

  ftp:
    container_name: ftp
    image: ftp:1337
    build:
      context: ./requirements/bonus/ftp
      dockerfile: Dockerfile
    depends_on:
      - wordpress
    volumes:
      - wordpress:/home/moseddik/ftp/files
    ports:
      - "20:20"
      - "21:21"
      - "3000-3010:3000-3010"
    networks:
      - inception
    restart: on-failure

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/moseddik/data/mariadb

  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/moseddik/data/wordpress

networks:
  inception:
