---
version: "3"
services:
  nginx:
    build:
      context : ./requirements/nginx
      dockerfile: Dockerfile
    container_name: c_ngnix
    ports:
      - "443:443"
    # volumes:
    #   - "/home/moseddik/data:/etc/nginx/http.d/"
    image: "ngnix:1337"
    restart: always
