---
version: "3"
services:

  nginx:
    build:
      context : ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www
    image: "ngnix:1337"
    networks:
      - inception
    restart: on-failure

  mariadb:
    build:
      context : ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    image: mariadb:1337
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql
    networks:
      - inception
    restart: on-failure

  wordpress:
    build:
      context : ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    depends_on:
      - mariadb
    image: wordpress:1337
    env_file:
      - .env
    volumes:
      - wordpress:/var/www
    networks:
      - inception
    restart: on-failure

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/moseddik/data/mariadb

  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/moseddik/data/wordpress

networks:
  inception:
